services:
  - type: web
    name: notehub-backend
    env: docker
    plan: free # or standard if you want persistent disks on Render
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: DB_PATH
        value: /app/notehub.db
      - key: SECRET_KEY
        generateValue: true

